// 登录弹窗
var bound_moblie_alert = '{$bound_moblie_alert|default="disabled"}';//第一次登陆
var str = '';
str +='<div id="tel_login_v1">';
str +=    '<!-- 弹窗背景 -->';
str +=    '<div class="bg" onclick="tel_login_v1.close()"></div>';
str +=    '<!-- 登录注册弹窗 -->';
str +=    '<div class="login-reg-wrapper pop-box pop-box1">';
str +=        '<!-- 诱导浏览器自动填充密码 -->';
str +=        '<input type="text" style="display:none;">';
str +=        '<input type="password" style="display:none;">';
str +=        '<div class="close-wrapper" onclick="tel_login_v1.close()"><img src="'+public_img_str+'/tel_login/close.png" class="close">';
str +=        '</div>';
str +=        '<div class="login-reg-title">';
str +=            '<span class="text on" onclick="tel_login_v1.showTab(0)">登录</span>';
str +=            '<span class="text" onclick="tel_login_v1.showTab(2)">注册</span>';
str +=        '</div>';
str +=        '<div class="login-content-wrapper">';
str +=            '<!-- 账号登录 -->';
str +=            '<div class="login-content-item" >';
str +=                '<div class="left">';
str +=                    '<div class="login-inp">';
str +=                        '<input class="user_mobile" type="text" maxlength="11" placeholder="手机号/靓号登录">';
str +=                    '</div>';
str +=                    '<div class="login-inp">';
str +=                        '<input class="user_pwd" onfocus="this.type=\'password\'" maxlength="20" placeholder="请输入密码">';
str +=                    '</div>';
str +=                    '<div class="auto_login">';
str +=                        '<span class="check-btn-wrapper on user-check" onclick="tel_login_v1.urserCheckFun()">';
str +=                            '<span class="check-btn"></span>';
str +=                            '<span class="check-text">下次自动登录</span>';
str +=                        '</span>';
str +=                        '<span class="find-pwd" onclick="tel_login_v1.bindPopShowFun(2)">找回密码</span>';
str +=                    '</div>';
str +=                    '<div class="login-inp "><div href="javascript:;" onclick="tel_login_v1.userLoginFun()" class="login-btn">登录</div></div>';
str +=                '</div>';
str +=                '<div class="right">';
str +=                    '<span class="right-title">其它登录方式</span>';
str +=                    '<div class="login-mode-wrapper ">';
str +=                        '<div class="login-mode-item one" onclick="tel_login_v1.showTab(1)">';
str +=                            '<img src="'+public_img_str+'/tel_login/phone.png" alt="" class="icon">';
str +=                            '<span class="text">短信登录</span>';
str +=                        '</div>';
str +=                        '<div class="login-mode-item two">';
str +=                            '<a href="/user/connect/authorize/platform/wechat">';
str +=                                '<img src="'+public_img_str+'/tel_login/wx.png" alt="" class="icon">';
str +=                                '<span class="text">微信登录</span>';
str +=                            '</a>';
str +=                        '</div>';
str +=                        '<div class="login-mode-item three">';
str +=                            '<a href="/user/connect/authorize/platform/qq">';
str +=                                '<img src="'+public_img_str+'/tel_login/qq.png" alt="" class="icon">';
str +=                                '<span class="text">QQ登录</span>';
str +=                            '</a>';
str +=                        '</div>';
str +=                    '</div>';
str +=                '</div>';
str +=                '<div class="bottom">';
str +=                    '<span class="check-btn-wrapper on regist-check1" onclick="tel_login_v1.registCheckFun1()">';
str +=                        '<span class="check-btn"></span>';
str +=                    '</span>';
str +=                    '<span class="text">阅读并同意<span class="agreement" onclick="tel_login_v1.agreement_fn(1);return false;">《刀锋电竞用户协议》</span>和<span class="agreement" onclick="tel_login_v1.agreement_fn(2)">《隐私协议》</span></span>';
str +=                '</div>';
str +=            '</div>';
str +=            '<!-- 短信登录 -->';
str +=            '<div class="login-content-item" >';
str +=                '<div class="left">';
str +=                    '<div class="login-inp msg-inp">';
str +=                        '<div class="regist_phone_code regist_phone_code1 msg_country_code"';
str +=                        'onclick="tel_login_v1.regist_ul_show(1)">+<span class="msg_country_code_text">86</span> <img src="'+public_img_str+'/tel_login/jt.png"';
str +=                                'alt=""></div>';
// 国际代码
str +='<div class="code_wrap regist_msg_code_wrap">';
str +=    '<div class="code_content">';
str +=    '<div class="search_top">';
str +=        '<i class="icon_search"></i>';
str +=        '<input type="text" class="search_code_inpt regist_msg_code_search_val" placeholder="搜索您的国家和地区">';
str +=    '</div>';
str +=    '<div class="list_wrap">';
str +=    '<div class="hot_wrap">';
str +=        '<div class="hot_bt">热门</div>';
str +=        '<div class="list">';
for (var i in PHONE_PREFIX.hot) {
    str +=            '<div class="li" onclick="tel_login_v1.check_ccode_fun('+i+',1,1)">';
    str +=                '<span class="code_name">'+PHONE_PREFIX.hot[i].cname+'</span>';
    str +=                '<span class="code_num">+'+PHONE_PREFIX.hot[i].areanum+'</span>';
    str +=            '</div>';
}
str +=        '</div>';
str +=        '<div class="line"></div>';
str +=    '</div>';
str +=    '<div class="list_all_wrap">';
str +=        '<div class="list">';
for (var i in PHONE_PREFIX.all) {
    str +=            '<div class="li" onclick="tel_login_v1.check_ccode_fun('+i+',1,0)">';
    str +=                '<span class="code_name">'+PHONE_PREFIX.all[i].cname+'</span>';
    str +=                '<span class="code_num">+'+PHONE_PREFIX.all[i].areanum+'</span>';
    str +=            '</div>';
}
str +=        '</div>';
str +=    '</div>';
str +=    '</div>';
str +=    '</div>';
str +='</div>';
str +=                        '<input class="msg_mobile" type="number" maxlength="11" placeholder="请输入手机号">';
str +=                    '</div>';
// str +=                    '<div class="login-inp img-code">';
// str +=                        '<div class="code-wrapper w200 msg-inp">';
// str +=                            '<input class="w177 msg_captcha_code" type="text" placeholder="请输入图形验证码">';
// str +=                        '</div>';
// str +=                        '<i class="code_txt">';
// str +=                            '<img class="security-code msg_captcha_img" onclick="tel_login_v1.refreshImgCode()">';
// str +=                        '</i>';
// str +=                    '</div>';
str +=                    '<div class="login-inp">';
str +=                        '<div class="code-wrapper w240 msg-inp">';
str +=                            '<input class="msg_message_code w218" type="text" onfocus="this.type=\'number\'" placeholder="请输入短信验证码" enter=\'msgLoginFun\'>';
str +=                        '</div>';
str +=                        '<i class="code_txt">';
str +=                            '<input type="button" class="msg_phone-security-code" data-appid="2058695242" data-cbfn="callback"  onclick="tel_login_v1.captcha_show(1)" value="获取验证码"/>';
str +=                        '</i>';
str +=                    '</div>';
str +=                    '<div class="login-inp  msg-inp pwd-inpt-wrap" >';
str +=                        '<input class="msg_pwd" maxlength="20" onfocus="this.type=\'password\'"';
str +=                            'placeholder="请输入密码">';
str +=                    '</div>';
str +=                    '<div class="login-inp msg-login-pwd" ><div onclick="tel_login_v1.msgLoginFun()" class="login-btn">登录</div></div>';
str +=                    '<div class="login-inp msg-login-nopwd" ><div onclick="tel_login_v1.setPassword(1)" class="login-btn">登录</div></div>';
str +=                '</div>';
str +=                '<div class="right">';
str +=                    '<span class="right-title">其它登录方式</span>';
str +=                    '<div class="login-mode-wrapper">';
str +=                        '<div class="login-mode-item one" onclick="tel_login_v1.showTab(0)">';
str +=                            '<img src="'+public_img_str+'/tel_login/user.png" alt="" class="icon">';
str +=                            '<span class="text">账号登录</span>';
str +=                        '</div>';
str +=                        '<div class="login-mode-item two">';
str +=                            '<a href="/user/connect/authorize/platform/wechat">';
str +=                                '<img src="'+public_img_str+'/tel_login/wx.png" alt="" class="icon">';
str +=                                '<span class="text">微信登录</span>';
str +=                            '</a>';
str +=                        '</div>';
str +=                        '<div class="login-mode-item three">';
str +=                            '<a href="/user/connect/authorize/platform/qq">';
str +=                                '<img src="'+public_img_str+'/tel_login/qq.png" alt="" class="icon">';
str +=                                '<span class="text">QQ登录</span>';
str +=                            '</a>';
str +=                        '</div>';
str +=                    '</div>';
str +=                '</div>';
str +=                '<div class="bottom">';
str +=                    '<span class="check-btn-wrapper on regist-check2" onclick="tel_login_v1.registCheckFun2()">';
str +=                        '<span class="check-btn"></span>';
str +=                    '</span>';
str +=                    '<span class="check-text">';
str +=                        '阅读并同意<span class="agreement" onclick=\'tel_login_v1.agreement_fn(1);return false;\'>《刀锋电竞用户协议》</span>和<span class="agreement" onclick="tel_login_v1.agreement_fn(2)">《隐私协议》</span></span>';
str +=                    '</span>';
str +=                '</div>';
str +=            '</div>';
str +=            '<!-- 注册 -->';
str +=            '<div class="login-content-item">';
str +=                '<div class="left">';
str +=                    '<div class="login-inp regist-inp">';
str +=                        '<div class="regist_phone_code regist_phone_code2"  onclick="tel_login_v1.regist_ul_show(2)">+<span class="regist_country_code_text">86</span>';
str +=                              '<img src="'+public_img_str+'/tel_login/jt.png" alt=""></div>';
// 国际代码
str +='<div class="code_wrap regedit_code_wrap">';
str +=    '<div class="code_content">';
str +=    '<div class="search_top">';
str +=        '<i class="icon_search"></i>';
str +=        '<input type="text" class="search_code_inpt regist_phone_code_search_val" placeholder="搜索您的国家和地区">';
str +=    '</div>';
str +=    '<div class="list_wrap">';
str +=    '<div class="hot_wrap">';
str +=        '<div class="hot_bt">热门</div>';
str +=        '<div class="list">';
for (var i in PHONE_PREFIX.hot) {
    str +=            '<div class="li" onclick="tel_login_v1.check_ccode_fun('+i+',2,1)">';
    str +=                '<span class="code_name">'+PHONE_PREFIX.hot[i].cname+'</span>';
    str +=                '<span class="code_num">+'+PHONE_PREFIX.hot[i].areanum+'</span>';
    str +=            '</div>';
}
str +=        '</div>';
str +=        '<div class="line"></div>';
str +=    '</div>';
str +=    '<div class="list_all_wrap">';
str +=        '<div class="list">';
for (var i in PHONE_PREFIX.all) {
    str +=            '<div class="li" onclick="tel_login_v1.check_ccode_fun('+i+',2,0)">';
    str +=                '<span class="code_name">'+PHONE_PREFIX.all[i].cname+'</span>';
    str +=                '<span class="code_num">+'+PHONE_PREFIX.all[i].areanum+'</span>';
    str +=            '</div>';
}
str +=        '</div>';
str +=    '</div>';
str +=    '</div>';
str +=    '</div>';
str +='</div>';
str +=                        '<input class="regist_mobile" type="text" v-model.trim=\'regist_mobile\' maxlength="11"';
str +=                            'placeholder="请输入手机号">';
str +=                    '</div>';
// str +=                    '<div class="login-inp img-code">';
// str +=                        '<div class="code-wrapper w200 regist-inp">';
// str +=                            '<input class="w177 regist_captcha_code" type="text" placeholder="请输入图形验证码">';
// str +=                        '</div>';
// str +=                        '<i class="code_txt">';
// str +=                            '<img class="security-code regist_captcha_img" onclick="tel_login_v1.refreshImgCode()">';
// str +=                        '</i>';
// str +=                    '</div>';
str +=                    '<div class="login-inp">';
str +=                        '<div class="code-wrapper w240 regist-inp">';
str +=                            '<input class="regist_message_code w218 " type="text" onfocus="this.type=\'number\'" placeholder="请输入短信验证码">';
str +=                        '</div>';
str +=                        '<i class="code_txt">';
str +=                            '<input type="button" class="regist_phone-security-code" data-appid="2058695242" data-cbfn="callback"  onclick="tel_login_v1.captcha_show(2)" value="获取验证码"/>';
str +=                        '</i>';
str +=                    '</div>';
str +=                    '<div class="login-inp regist-inp">';
str +=                        '<input class="regist_pwd" maxlength="20" onfocus="this.type=\'password\'" placeholder="请输入密码">';
str +=                    '</div>';
str +=                    '<div class="login-inp"><div onclick="tel_login_v1.register()" class="login-btn">注册</div></div>';
str +=                '</div>';
str +=                '<div class="right">';
str +=                    '<span class="right-title">其它登录方式</span>';
str +=                    '<div class="login-mode-wrapper">';
str +=                        '<div class="login-mode-item one" onclick="tel_login_v1.showTab(1)">';
str +=                            '<img src="'+public_img_str+'/tel_login/phone.png" alt="" class="icon">';
str +=                            '<span class="text">短信登录</span>';
str +=                        '</div>';
str +=                        '<div class="login-mode-item two">';
str +=                            '<a href="/user/connect/authorize/platform/wechat">';
str +=                                '<img src="'+public_img_str+'/tel_login/wx.png" alt="" class="icon">';
str +=                                '<span class="text">微信登录</span>';
str +=                            '</a>';
str +=                        '</div>';
str +=                        '<div class="login-mode-item three">';
str +=                            '<a href="/user/connect/authorize/platform/qq">';
str +=                                '<img src="'+public_img_str+'/tel_login/qq.png" alt="" class="icon">';
str +=                                '<span class="text">QQ登录</span>';
str +=                            '</a>';
str +=                        '</div>';
str +=                    '</div>';
str +=                '</div>';
str +=                '<div class="bottom">';
str +=                    '<span class="check-btn-wrapper on regist-check" onclick="tel_login_v1.registCheckFun()">';
str +=                        '<span class="check-btn"></span>';
str +=                    '</span>';
str +=                        '<span class="check-text">';
str +=                            '注册即同意<span class="agreement" onclick=\'tel_login_v1.agreement_fn(1);return false;\'>《刀锋电竞用户协议》</span>和<span class="agreement" onclick="tel_login_v1.agreement_fn(2)">《隐私协议》</span></span>';
str +=                        '</span>';
str +=                '</div>';
str +=            '</div>';
str +=        '</div>';
str +=    '</div>';
str +=    '<!-- 忘记密码 -->';
str +=    '<div class="login-reg-wrapper forget pop-box pop-box2">';
str +=        '<div class="close-wrapper" onclick="tel_login_v1.close()"><img src="'+public_img_str+'/tel_login/close.png" class="close"></div>';
str +=        '<div class="login-reg-title">';
str +=            '<span class="return-btn" onclick="tel_login_v1.bindPopShowFun(1)"><img class="icon" src="'+public_img_str+'/back.png" alt="">返回</span>';
str +=            '<span class="text">找回密码</span>';
str +=        '</div>';
str +=        '<div class="login-content-wrapper">';
str +=            '<div class="login-content-item ">';
str +=                '<div class="left">';
str +=                    '<div class="login-inp reset-inp">';
str +=                        '<div class="regist_phone_code regist_phone_code3" onclick="tel_login_v1.regist_ul_show(3)">';
str +=                        '+<span class="reset_country_code_text">86</span>';
str +=                        '<img src="'+public_img_str+'/tel_login/jt.png" alt=""></div>';
// 国际代码
str +='<div class="code_wrap regist_reset_code_wrap">';
str +=    '<div class="code_content">';
str +=    '<div class="search_top">';
str +=        '<i class="icon_search"></i>';
str +=        '<input type="text" class="search_code_inpt regist_reset_code_search_val" placeholder="搜索您的国家和地区">';
str +=    '</div>';
str +=    '<div class="list_wrap">';
str +=    '<div class="hot_wrap">';
str +=        '<div class="hot_bt">热门</div>';
str +=        '<div class="list">';
for (var i in PHONE_PREFIX.hot) {
    str +=            '<div class="li" onclick="tel_login_v1.check_ccode_fun('+i+',3,1)">';
    str +=                '<span class="code_name">'+PHONE_PREFIX.hot[i].cname+'</span>';
    str +=                '<span class="code_num">+'+PHONE_PREFIX.hot[i].areanum+'</span>';
    str +=            '</div>';
}
str +=        '</div>';
str +=        '<div class="line"></div>';
str +=    '</div>';
str +=    '<div class="list_all_wrap">';
str +=        '<div class="list">';
for (var i in PHONE_PREFIX.all) {
    str +=            '<div class="li" onclick="tel_login_v1.check_ccode_fun('+i+',3,0)">';
    str +=                '<span class="code_name">'+PHONE_PREFIX.all[i].cname+'</span>';
    str +=                '<span class="code_num">+'+PHONE_PREFIX.all[i].areanum+'</span>';
    str +=            '</div>';
}
str +=        '</div>';
str +=    '</div>';
str +=    '</div>';
str +=    '</div>';
str +='</div>';

str +=                        '<input class="reset_mobile" type="text" maxlength="11" placeholder="请输入手机号">';
str +=                    '</div>';
str +=                    '<div class="login-inp img-code">';
str +=                        '<div class="code-wrapper w200 reset-inp">';
str +=                            '<input class="w177 reset_captcha_code" type="text" placeholder="请输入图形验证码">';
str +=                        '</div>';
str +=                        '<i class="code_txt">';
str +=                            '<img class="security-code" onclick="tel_login_v1.refreshImgCode()">';
str +=                        '</i>';
str +=                    '</div>';
str +=                    '<div class="login-inp">';
str +=                        '<div class="code-wrapper w240 reset-inp">';
str +=                            '<input class="reset_message_code w218 " type="text" onfocus="this.type=\'number\'" placeholder="请输入短信验证码">';
str +=                        '</div>';
str +=                        '<i class="code_txt">';
str +=                            '<input type="button" class="reset_phone-security-code" onclick=\'tel_login_v1.sendmessageFun(5)\' value="获取验证码"/>';
str +=                        '</i>';
str +=                    '</div>';
str +=                    '<div class="login-inp reset-inp">';
str +=                        '<input class="reset_pwd" maxlength="20" onfocus="this.type=\'password\'" placeholder="请输入密码">';
str +=                    '</div>';
str +=                    '<div class="login-inp reset-inp">';
str +=                        '<input class="reset_re_pwd" maxlength="20" onfocus="this.type=\'password\'" placeholder="请输入密码">';
str +=                    '</div>';
str +=                    '<div class="login-inp "><a href="javascript:;" onclick="tel_login_v1.password_find()" class="login-btn">重置密码</a></div>';
str +=                '</div>';
str +=            '</div>';
str +=        '</div>';
str +=    '</div>';
str +=    '<!-- 绑定手机号 -->';
str +=    '<div class="login-reg-wrapper forget bind pop-box pop-box3">';
// str +=        '<div class="close-wrapper" onclick="tel_login_v1.close()"><img src="'+public_img_str+'/tel_login/close.png" class="close"></div>';
// str +=        '<div class="skip-btn" onclick="tel_login_v1.bindPopShowFun(12)">跳过</div>';
str +=        '<div class="login-reg-title">';
str +=            '<span class="text">绑定手机号</span>';
str +=            '<p class="desc">绑定手机可以大幅度提高安全性，还可以解锁更多新功能呢</p>';
str +=        '</div>';
str +=        '<div class="login-content-wrapper">';
str +=            '<div class="login-content-item ">';
str +=                '<div class="left">';
str +=                    '<div class="login-inp bind-inp">';
str +=                        '<div class="regist_phone_code regist_phone_code4" onclick="tel_login_v1.regist_ul_show(4)">';
str +=                            '+<span class="bind_country_code_text">86</span>';
str +=                            '<img src="'+public_img_str+'/tel_login/jt.png" alt="">';
str +=                        '</div>';
// 国际代码
str +='<div class="code_wrap regist_bind_code_wrap">';
str +=    '<div class="code_content">';
str +=    '<div class="search_top">';
str +=        '<i class="icon_search"></i>';
str +=        '<input type="text" class="search_code_inpt regist_bind_code_search_val" placeholder="搜索您的国家和地区">';
str +=    '</div>';
str +=    '<div class="list_wrap">';
str +=    '<div class="hot_wrap">';
str +=        '<div class="hot_bt">热门</div>';
str +=        '<div class="list">';
for (var i in PHONE_PREFIX.hot) {
    str +=            '<div class="li" onclick="tel_login_v1.check_ccode_fun('+i+',4,1)">';
    str +=                '<span class="code_name">'+PHONE_PREFIX.hot[i].cname+'</span>';
    str +=                '<span class="code_num">+'+PHONE_PREFIX.hot[i].areanum+'</span>';
    str +=            '</div>';
}
str +=        '</div>';
str +=        '<div class="line"></div>';
str +=    '</div>';
str +=    '<div class="list_all_wrap">';
str +=        '<div class="list">';
for (var i in PHONE_PREFIX.all) {
    str +=            '<div class="li" onclick="tel_login_v1.check_ccode_fun('+i+',4,0)">';
    str +=                '<span class="code_name">'+PHONE_PREFIX.all[i].cname+'</span>';
    str +=                '<span class="code_num">+'+PHONE_PREFIX.all[i].areanum+'</span>';
    str +=            '</div>';
}
str +=        '</div>';
str +=    '</div>';
str +=    '</div>';
str +=    '</div>';
str +='</div>';
str +=                        '<input class="bind_mobile " type="text" maxlength="11" placeholder="请输入手机号">';
str +=                    '</div>';
str +=                    '<div class="login-inp img-code">';
str +=                        '<div class="code-wrapper w200 bind-inp">';
str +=                            '<input class="w177 bind_captcha_code" type="text" placeholder="请输入图形验证码">';
str +=                        '</div>';
str +=                        '<i class="code_txt">';
str +=                            '<img class="security-code" onclick="tel_login_v1.refreshImgCode()">';
str +=                        '</i>';
str +=                    '</div>';
str +=                    '<div class="login-inp">';
str +=                        '<div class="code-wrapper w240 bind-inp">';
str +=                            '<input class="bind_message_code w218 " type="text" onfocus="this.type=\'number\'" placeholder="请输入短信验证码">';
str +=                        '</div>';
str +=                        '<i class="code_txt">';
str +=                            '<input type="button" class="bind_phone-security-code"  onclick=\'tel_login_v1.sendmessageFun(3)\' value="获取验证码"/>';
str +=                        '</i>';
str +=                    '</div>';
str +=                    '<div class="login-inp bind-inp bind-pwd">';
str +=                        '<input class="bind_pwd" maxlength="20" onfocus="this.type=\'password\'" placeholder="请输入密码">';
str +=                    '</div>';
str +=                    '<div class="login-inp bind-btn-pwd" ><div onclick="tel_login_v1.bindFun(0)" class="login-btn">绑定</div></div>';
str +=                    '<div class="login-inp btn_color1 bind-btn-nopwd"><div onclick="tel_login_v1.setPassword(2)" class="login-btn">绑定</div></div>';
str +=                '</div>';
str +=            '</div>';
str +=        '</div>';
str +=    '</div>';
str +=    '<!-- 绑定其它手机号  -->';
str +=    '<div class="login-reg-wrapper forget bind pop-box pop-box4">';
// str +=        '<div class="close-wrapper" onclick="tel_login_v1.close()"><img src="'+public_img_str+'/tel_login/close.png" class="close"></div>';
str +=        '<div class="login-reg-title">';
str +=            '<span class="text">绑定手机号</span>';
str +=        '</div>';
str +=        '<div class="login-content-wrapper">';
str +=            '<div class="login-content-item ">';
str +=                '<div class="left">';
str +=                    '<div class="login-inp bind-other-inp">';
str +=                        '<div class="regist_phone_code regist_phone_code5" onclick="tel_login_v1.regist_ul_show(5)">';
str +=                            '+<span class="bind_other_country_code_text">86</span>';
str +=                            '<img src="'+public_img_str+'/tel_login/jt.png" alt="">';
str +=                        '</div>';
// 国际代码
str +='<div class="code_wrap regist_bind_other_code_wrap">';
str +=    '<div class="code_content">';
str +=    '<div class="search_top">';
str +=        '<i class="icon_search"></i>';
str +=        '<input type="text" class="search_code_inpt regist_bind_other_code_search_val" placeholder="搜索您的国家和地区">';
str +=    '</div>';
str +=    '<div class="list_wrap">';
str +=       '<div class="hot_wrap">';
str +=        '<div class="hot_bt">热门</div>';
str +=        '<div class="list">';
for (var i in PHONE_PREFIX.hot) {
    str +=            '<div class="li" onclick="tel_login_v1.check_ccode_fun('+i+',5,1)">';
    str +=                '<span class="code_name">'+PHONE_PREFIX.hot[i].cname+'</span>';
    str +=                '<span class="code_num">+'+PHONE_PREFIX.hot[i].areanum+'</span>';
    str +=            '</div>';
}
str +=        '</div>';
str +=        '<div class="line"></div>';
str +=    '</div>';
str +=    '<div class="list_all_wrap">';
str +=        '<div class="list">';
for (var i in PHONE_PREFIX.all) {
    str +=            '<div class="li" onclick="tel_login_v1.check_ccode_fun('+i+',5,0)">';
    str +=                '<span class="code_name">'+PHONE_PREFIX.all[i].cname+'</span>';
    str +=                '<span class="code_num">+'+PHONE_PREFIX.all[i].areanum+'</span>';
    str +=            '</div>';
}
str +=        '</div>';
str +=    '</div>';
str +=    '</div>';
str +=    '</div>';
str +='</div>';
str +=                        '<input class="bind_other_mobile" type="text" maxlength="11" placeholder="请输入手机号">';
str +=                    '</div>';
str +=                    '<div class="login-inp img-code">';
str +=                        '<div class="code-wrapper w200 bind-other-inp">';
str +=                            '<input class="w177 bind_other_captcha_code" type="text" placeholder="请输入图形验证码">';
str +=                        '</div>';
str +=                        '<i class="code_txt">';
str +=                            '<img class="security-code" onclick="tel_login_v1.refreshImgCode()">';
str +=                        '</i>';
str +=                    '</div>';
str +=                    '<div class="login-inp">';
str +=                        '<div class="code-wrapper w240 bind-other-inp">';
str +=                            '<input class="bind_other_message_code w218 " type="text" onfocus="this.type=\'number\'" placeholder="请输入短信验证码">';
str +=                        '</div>';
str +=                        '<i class="code_txt">';
str +=                            '<input type="button" class="bind_other_phone-security-code" onclick=\'tel_login_v1.sendmessageFun(4)\'  value="获取验证码"/>';
str +=                        '</i>';
str +=                    '</div>';
str +=                    '<div class="login-inp bind-other-inp bind-other-pwd">';
str +=                        '<input class="bind_other_pwd" maxlength="20" onfocus="this.type=\'password\'" placeholder="请输入密码">';
str +=                    '</div>';
str +=                    '<div class="login-inp bind-other-btn-pwd" ><div onclick=\'tel_login_v1.bindFun(2)\' class="login-btn">绑定</div></div>';
str +=                    '<div class="login-inp btn_color1 bind-other-btn-nopwd"><div onclick="tel_login_v1.setPassword(3)" class="login-btn">绑定</div></div>';
str +=                '</div>';
str +=            '</div>';
str +=        '</div>';
str +=    '</div>';
str +=    '<!-- 绑定成功 -->';
str +=    '<div class="bind-success-wrapper pop-box pop-box5">';
str +=        '<div class="close-wrapper" onclick="tel_login_v1.close()"><img src="'+public_img_str+'/tel_login/close.png" class="close"></div>';
str +=        '<div class="content-wrapper">';
str +=            '<div class="icon-wrapper">';
str +=                '<img src="'+public_img_str+'/tel_login/success.png" alt="" class="icon">';
str +=            '</div>';
str +=            '<span class="title">恭喜您绑定成功 </span>';
str +=            '<span class="text">您可通过手机号和密码登录</span>';
str +=        '</div>';
str +=    '</div>';
str +=    '<!-- 没有绑定手机号绑定 -->';
str +=    '<div class="pop-wrapper pop-box pop-box6">';
str +=        '<div class="content-wrapper">';
str +=            '<div class="pop-title">';
str +=                '<img class="icon-warn" src="'+public_img_str+'/tel_login/icon_notice.png" />';
str +=            '</div>';
str +=            '<div class="desc-wrapper">';
str +=                '<span class="title">亲爱的用户</span>';
str +=                '<span class="desc">您尚未绑定手机号，是否绑定？</span>';
str +=            '</div>';
str +=            '<div class="btn-wrapper">';
str +=                '<div class="copy-btn btn" onclick="tel_login_v1.close()">暂不绑定</div>';
str +=                '<div class="url-btn btn" onclick="tel_login_v1.bindPopShowFun(3)">绑定手机号</div>';
str +=            '</div>';
str +=        '</div>';
str +=    '</div>';
str +=    '<!-- 数据库存在继续绑定 -->';
str +=    '<div class="pop-wrapper pop-box pop-box7">';
str +=        '<div class="content-wrapper">';
str +=            '<div class="pop-title">';
str +=                '<img class="icon-warn" src="'+public_img_str+'/tel_login/icon_notice.png" />';
str +=            '</div>';
str +=            '<div class="desc-wrapper">';
str +=                '<span class="title">亲爱的用户</span>';
str +=                '<span class="desc" style="text-align: left">';
str +=                    '1. 该手机号已在平台注册。<br>';
str +=                    '2. 如绑定该手机号，您的账户余额、贡献值、魅力值信息将会转移到手机号账户下;<br>';
str +=                    '3. 当前账号订单明细、资金明细不会保留;';
str +=                '</span>';
str +=            '</div>';
str +=            '<div class="btn-wrapper">';
str +=                '<div class="copy-btn btn" onclick="tel_login_v1.close()">暂不绑定</div>';
str +=                '<div class="url-btn btn" onclick="tel_login_v1.bindFun(1)">继续绑定</div>';
str +=            '</div>';
str +=        '</div>';
str +=    '</div>';
str +=    '<!-- 绑定账号有未完成订单弹窗 -->';
str +=    '<div class="pop-wrapper pop-box pop-box8">';
str +=        '<div class="content-wrapper">';
str +=            '<div class="pop-title">';
str +=                '<img class="icon-warn" src="'+public_img_str+'/tel_login/icon_notice.png" />';
str +=            '</div>';
str +=            '<div class="desc-wrapper">';
str +=                '<span class="title">亲爱的用户</span>';
str +=                '<span class="desc">';
str +=                    '您当前账户或绑定的手机号账户有未完成订单，请在订单完成后再进行账户绑定。';
str +=                '</span>';
str +=            '</div>';
str +=            '<div class="btn-wrapper">';
str +=                '<div class="copy-btn btn" onclick="tel_login_v1.close()">暂不绑定</div>';
str +=                '<div class="url-btn btn" onclick="tel_login_v1.bindPopShowFun(4)">绑定其它手机号</div>';
str +=            '</div>';
str +=        '</div>';
str +=    '</div>';
str +=    '<!-- 申请入驻未绑定手机号 -->';
str +=    '<div class="pop-wrapper pop-box pop-box9">';
str +=        '<div class="content-wrapper">';
str +=            '<div class="pop-title">';
str +=                '<img class="icon-warn" src="'+public_img_str+'/tel_login/icon_notice.png" />';
str +=            '</div>';
str +=            '<div class="desc-wrapper">';
str +=                '<span class="title">亲爱的用户</span>';
str +=                '<span class="desc">申请入驻陪玩，需绑定手机号，以便有突发状态时，客服联系您</span>';
str +=            '</div>';
str +=            '<div class="btn-wrapper">';
str +=                '<div class="copy-btn btn" onclick="tel_login_v1.close">暂不入驻</div>';
str +=                '<div class="url-btn btn" onclick="tel_login_v1.bindPopShowFun(4)">绑定手机号</div>';
str +=            '</div>';
str +=        '</div>';
str +=    '</div>';
str +=    '<!-- 送礼物未绑定手机号 -->';
str +=    '<div class="pop-wrapper pop-box pop-box10">';
str +=        '<div class="content-wrapper">';
str +=            '<div class="pop-title">';
str +=                '<img class="icon-warn" src="'+public_img_str+'/tel_login/icon_notice.png" />';
str +=            '</div>';
str +=            '<div class="desc-wrapper">';
str +=                '<span class="title">亲爱的用户</span>';
str +=                '<span class="desc">只有绑定了手机号后,才能送礼物哦~</span>';
str +=            '</div>';
str +=            '<div class="btn-wrapper">';
str +=                '<div class="copy-btn btn" onclick="tel_login_v1.close">暂不绑定</div>';
str +=                '<div class="url-btn btn" onclick="tel_login_v1.bindPopShowFun(4)">绑定手机号</div>';
str +=            '</div>';
str +=        '</div>';
str +=    '</div>';
str +=    '<!-- 设置密码 -->';
str +=    '<div class="login-reg-wrapper forget setpwd pop-box pop-box11">';
str +=        '<div class="close-wrapper" onclick="tel_login_v1.close()"><img src="'+public_img_str+'/tel_login/close.png" class="close"></div>';
str +=        '<div class="login-reg-title">';
str +=            '<span class="text">设置密码</span>';
str +=        '</div>';
str +=        '<div class="login-content-wrapper">';
str +=            '<div class="login-content-item ">';
str +=                '<div class="left">';
str +=                    '<div class="login-inp set-pwd-inp">';
str +=                        '<input class="set_pwd" maxlength="20" onfocus="this.type=\'password\'" placeholder="请输入密码">';
str +=                    '</div>';
str +=                    '<div class="login-inp btn_color1">';
str +=                        '<div  onclick="tel_login_v1.setPassword(4)" class="login-btn">设置</div>';
str +=                    '</div>';
str +=                '</div>';
str +=            '</div>';
str +=        '</div>';
str +=    '</div>';
str +=    '<!-- 选择性别 -->';
str +=    '<div class="login-reg-wrapper forget sex pop-box pop-box12">';
str +=        '<div class="login-reg-title">';
str +=            '<span class="text">请选择您的性别</span>';
str +=            '<p class="desc">性别一旦选择就无法更改</p>';
str +=        '</div>';
str +=        '<div class="login-content-wrapper">';
str +=            '<div class="login-content-item ">';
str +=                '<div class="left">';
str +=                    '<div class="sex-wrapper">';
str +=                        '<div class="sex-i" onclick="tel_login_v1.checkSexFun(1,this)">';
str +=                            '<img src="'+public_img_str+'/tel_login/nan.png" alt="" class="sex-img">';
str +=                            '<img src="'+public_img_str+'/tel_login/nan_hover.png" alt="" class="sex-img-hover">';
str +=                        '</div>';
str +=                        '<div class="sex-i" onclick="tel_login_v1.checkSexFun(2,this)">';
str +=                            '<img src="'+public_img_str+'/tel_login/nv.png" alt="" class="sex-img">';
str +=                            '<img src="'+public_img_str+'/tel_login/nv_hover.png" alt="" class="sex-img-hover">';
str +=                        '</div>';
str +=                    '</div>';
str +=                    '<div class="login-inp btn_color1">';
str +=                        '<div onclick="tel_login_v1.saveSexFun()" class="login-btn">确定</div>';
str +=                    '</div>';
str +=                '</div>';
str +=            '</div>';
str +=        '</div>';
str +=    '</div>';
str += '</div>';
str +='</div>';

//性别选择
str +='<div class="public-sex">';
str +=    '<div class="lable-con">';
str +=        '<p>选择您的性别</p>';
str +=        '<div class="tips">性别一旦选择便无法更改哟~</div>';
str +=        '<ul class="sex-ul">';
str +=            '<li class="boyli" data="1">';
str +=                '<div class="img"></div>';
str +=                '男';
str +=                '<div class="btn" onclick="tel_login_v1.checkSexFun(1)"></div>';
str +=            '</li>';
str +=            '<li class="girlli" data="2">';
str +=                '<div class="img"></div>';
str +=                '女';
str +=                '<div class="btn" onclick="tel_login_v1.checkSexFun(2)"></div>';
str +=            '</li>';
str +=        '</ul>';
str +=        '<input class="nickname" maxlength="8" type="text" value="" placeholder="为自己取个好听的昵称吧！">';
str +=        '<button>下一步</button>';
str +=    '</div>';
str +='</div>';
//标签选择
str +='<div class="public-label">';
str +=    '<div class="lable-con">';
str +=        '<p class="no_pw_msg">选择您的喜好，我们为您';
str +=            '<span class="lab">匹配最适合的TA</span>';
str +=            '<span class="right">跳过<img src="'+public_img_str+'/nav_v3/ico_12.png" alt=""></span>';
str +=        '</p>';
str +=        '<p class="pw_msg">您的入驻申请已通过审核，快完善标签；';
str +=            '<span class="lab">让TA更快找到你吧</span>';
str +=        '</p>';
str +=        '<ul msg="标签" class="label-ul">';
str +=        '</ul>';
str +=        '<button><span class="label_this_num">0</span>/5 确定</button>';
str +=    '</div>';
str +='</div>';

//等级升级弹窗
str +='<div class="public_up_level">' ;
str +=    '<div class="up_level_box">' ;
str +=        '<div class="close_btn" onclick="tel_login_v1.close_level_pop()"></div>' ;
str +=        '<div class="level_box">Lv<em id="u_big_level">0</em></div>' ;
str +=        '<div class="hint_title">恭喜您</div>' ;
str +=        '<div class="hint_sub_title">用户等级升级至<span>Lv<em id="u_sub_level">0</em></span></div>' ;
str +=        '<a class="up_level_btn" href="/user/usercenter/index">查看我的特权</a>' ;
str +=    '</div>' ;
str +='</div>';


document.write(str);