package com.direct.est.entity;
// Generated 2019-12-13 10:36:57 by Hibernate Tools 5.4.7.Final

/**
 * 评价
 * Appraise generated by hbm2java
 */
public class Appraise implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Order order; 
	private Integer order_id;//订单id
 	private String neirong;//内容
	private String dengji;//星级

	public Appraise() {
	}

	public Appraise(int id) {
		this.id = id;
	}
	
	public Appraise(String neirong, String dengji) {
		super();
		this.neirong = neirong;
		this.dengji = dengji;
	}

	public Appraise(Order order, Integer order_id, String neirong, String dengji) {
		super();
		this.order = order;
		this.order_id = order_id;
		this.neirong = neirong;
		this.dengji = dengji;
	}

	public Appraise(int id, Order order, String neirong, String dengji) {
		this.id = id;
		this.order = order;
		this.neirong = neirong;
		this.dengji = dengji;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	

	public String getNeirong() {
		return neirong;
	}

	public void setNeirong(String neirong) {
		this.neirong = neirong;
	}

	public String getDengji() {
		return dengji;
	}

	public void setDengji(String dengji) {
		this.dengji = dengji;
	}

	public Integer getOrder_id() {
		return order_id;
	}

	public void setOrder_id(Integer order_id) {
		this.order_id = order_id;
	}

}
