package com.direct.est.entity;
// Generated 2019-12-21 10:50:46 by Hibernate Tools 5.4.7.Final


/**
 * Banner generated by hbm2java
 */
public class Banner implements java.io.Serializable {

	private int id;
	private Menu menu;
	private Integer menu_id;
	private String image;
	private String imgName;
	private Integer orderby;

	public Banner() {
	}

	public Banner(int id) {
		this.id = id;
	}
	
	
	
	

	public Banner(Integer menu_id, String image, String imgName) {
		super();
		this.menu_id = menu_id;
		this.image = image;
		this.imgName = imgName;
	}

	public Banner(int id, Menu menu, String image, String imgName, Integer orderby) {
		this.id = id;
		this.menu = menu;
		this.image = image;
		this.imgName = imgName;
		this.orderby = orderby;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getImgName() {
		return this.imgName;
	}

	public void setImgName(String imgName) {
		this.imgName = imgName;
	}

	public Integer getOrderby() {
		return this.orderby;
	}

	public void setOrderby(Integer orderby) {
		this.orderby = orderby;
	}

	public Integer getMenu_id() {
		return menu_id;
	}

	public void setMenu_id(Integer menu_id) {
		this.menu_id = menu_id;
	}
}
