package com.direct.est.entity;
// Generated 2019-12-13 10:36:57 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * 员工信息
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private int id;
	private String headImg;//头像
	private String home; //地址
	private String serveup; //服务介绍
	private String descy; //备注
	private String name;//真实姓名
	private String nickname;//昵称
	private String phone;//手机
	private String password;//密码
	private String sex;//性别
	private String age;//年龄
	private String state;//状态
	private Float price;//价格
	
	private Set employeetypes = new HashSet(0);
	private Set orders = new HashSet(0);
	private Set employeelbels = new HashSet(0);

	public Employee() {
	}

	
	public Employee(String name, String nickname) {
		super();
		this.name = name;
		this.nickname = nickname;
	}


	public Employee(int id) {
		this.id = id;
	}

	public Employee(int id, String name, String nickname, String phone, String password, String sex, String age,
			String state, Float price, String headImg, String home, String serveup, String descy, Set employeetypes,
			Set orders, Set employeelbels) {
		this.id = id;
		this.name = name;
		this.nickname = nickname;
		this.phone = phone;
		this.password = password;
		this.sex = sex;
		this.age = age;
		this.state = state;
		this.price = price;
		this.headImg = headImg;
		this.home = home;
		this.serveup = serveup;
		this.descy = descy;
		this.employeetypes = employeetypes;
		this.orders = orders;
		this.employeelbels = employeelbels;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public String getHeadImg() {
		return this.headImg;
	}

	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

	public String getHome() {
		return this.home;
	}

	public void setHome(String home) {
		this.home = home;
	}

	public String getServeup() {
		return this.serveup;
	}

	public void setServeup(String serveup) {
		this.serveup = serveup;
	}

	public String getDescy() {
		return this.descy;
	}

	public void setDescy(String descy) {
		this.descy = descy;
	}

	public Set getEmployeetypes() {
		return this.employeetypes;
	}

	public void setEmployeetypes(Set employeetypes) {
		this.employeetypes = employeetypes;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

	public Set getEmployeelbels() {
		return this.employeelbels;
	}

	public void setEmployeelbels(Set employeelbels) {
		this.employeelbels = employeelbels;
	}

}
