package com.direct.est.entity;
// Generated 2019-12-13 10:36:57 by Hibernate Tools 5.4.7.Final

/**
 * //员工类型
 * Employeetype generated by hbm2java
 */
public class Employeetype implements java.io.Serializable {

	private int id;
	private Employee employee;//类型id
	private Greamtype greamtype;//员工Id

	public Employeetype() {
	}

	public Employeetype(int id) {
		this.id = id;
	}

	public Employeetype(int id, Employee employee, Greamtype greamtype) {
		this.id = id;
		this.employee = employee;
		this.greamtype = greamtype;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Greamtype getGreamtype() {
		return this.greamtype;
	}

	public void setGreamtype(Greamtype greamtype) {
		this.greamtype = greamtype;
	}

}
