package com.direct.est.entity;
// Generated 2019-12-13 10:36:57 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * //游戏类型
 * Greamtype generated by hbm2java
 */
public class Greamtype implements java.io.Serializable {

	private int id;
	private String greamName;
	private String descy;
	
	
	private Set employeetypes = new HashSet(0);
	private Set greamlevels = new HashSet(0);

	public Greamtype() {
	}

	public Greamtype(int id) {
		this.id = id;
	}
	
	public Greamtype(String greamName, String descy) {
		super();
		this.greamName = greamName;
		this.descy = descy;
	}

	public Greamtype(int id, String greamName, String descy) {
		super();
		this.id = id;
		this.greamName = greamName;
		this.descy = descy;
	}

	public Greamtype(int id, String greamName, String descy, Set employeetypes, Set greamlevels) {
		this.id = id;
		this.greamName = greamName;
		this.descy = descy;
		this.employeetypes = employeetypes;
		this.greamlevels = greamlevels;
	}
	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getGreamName() {
		return this.greamName;
	}

	public void setGreamName(String greamName) {
		this.greamName = greamName;
	}

	public String getDescy() {
		return this.descy;
	}

	public void setDescy(String descy) {
		this.descy = descy;
	}

	public Set getEmployeetypes() {
		return this.employeetypes;
	}

	public void setEmployeetypes(Set employeetypes) {
		this.employeetypes = employeetypes;
	}

	public Set getGreamlevels() {
		return this.greamlevels;
	}

	public void setGreamlevels(Set greamlevels) {
		this.greamlevels = greamlevels;
	}

}
