package com.direct.est.entity;
// Generated 2019-12-13 10:36:57 by Hibernate Tools 5.4.7.Final

/**
 * 游戏等级
 * Greamlevel generated by hbm2java
 */
public class Greamlevel implements java.io.Serializable {

	private int id;
	private Greamtype greamtype; 
	private Integer greamType_id;//游戏类型id
	private String levelname;
	private String descy;

	public Greamlevel() {
	}

	public Greamlevel(int id) {
		this.id = id;
	}
	
	
	public Greamlevel(Integer greamType_id, String levelname, String descy) {
		super();
		this.greamType_id = greamType_id;
		this.levelname = levelname;
		this.descy = descy;
	}

	public Greamlevel(int id, Greamtype greamtype, String levelname) {
		super();
		this.id = id;
		this.greamtype = greamtype;
		this.levelname = levelname;
	}

	public Greamlevel(int id, Greamtype greamtype, String levelname, String descy) {
		this.id = id;
		this.greamtype = greamtype;
		this.levelname = levelname;
		this.descy = descy;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Greamtype getGreamtype() {
		return this.greamtype;
	}

	public void setGreamtype(Greamtype greamtype) {
		this.greamtype = greamtype;
	}

	public String getLevelname() {
		return this.levelname;
	}

	public void setLevelname(String levelname) {
		this.levelname = levelname;
	}

	public String getDescy() {
		return this.descy;
	}

	public void setDescy(String descy) {
		this.descy = descy;
	}

	public Integer getGreamType_id() {
		return greamType_id;
	}

	public void setGreamType_id(Integer greamType_id) {
		this.greamType_id = greamType_id;
	}
	
	
}
