package com.direct.est.entity;
// Generated 2019-12-13 10:36:57 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * 标签表
 * Label generated by hbm2java
 */
public class Label implements java.io.Serializable {

	private int id;
	private String labelname;
	private String descy;
	private Set userlabels = new HashSet(0);
	private Set employeelbels = new HashSet(0);

	public Label() {
	}

	public Label(int id) {
		this.id = id;
	}

	public Label(int id, String labelname, String descy, Set userlabels, Set employeelbels) {
		this.id = id;
		this.labelname = labelname;
		this.descy = descy;
		this.userlabels = userlabels;
		this.employeelbels = employeelbels;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLabelname() {
		return this.labelname;
	}

	public void setLabelname(String labelname) {
		this.labelname = labelname;
	}

	public String getDescy() {
		return this.descy;
	}

	public void setDescy(String descy) {
		this.descy = descy;
	}

	public Set getUserlabels() {
		return this.userlabels;
	}

	public void setUserlabels(Set userlabels) {
		this.userlabels = userlabels;
	}

	public Set getEmployeelbels() {
		return this.employeelbels;
	}

	public void setEmployeelbels(Set employeelbels) {
		this.employeelbels = employeelbels;
	}

}
