package com.direct.est.entity;
// Generated 2019-12-21 11:01:37 by Hibernate Tools 5.4.7.Final

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private int id;
	private String menuName;
	private String url;

	public Menu() {
	}

	
	public Menu(String menuName) {
		super();
		this.menuName = menuName;
	}

	public Menu(int id, String menuName, String url) {
		this.id = id;
		this.menuName = menuName;
		this.url = url;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
