package com.direct.est.entity;
// Generated 2019-12-13 10:36:57 by Hibernate Tools 5.4.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {
	  /**
	    * order表中有一个employee_id字段，所以在order类中定义一个employee属性，
	    * 用于维护订单和员工之间的一对一关系，
	    * 通过这个employee属性就可以知道这个订单是由哪个员工负责的
	    * User同理
	    * */
	private int id;
	private Employee employee;
	private Integer employee_id;//员工id
	private User user; 
	private Integer user_id;//用户id
	private Date hour;//订单生成时间
	private Integer number;//数量
	private Float money; //价格
	private String bascy;//备注
	
	 
	private Set appraises = new HashSet(0);

	public Order() {
	}

	public Order(int id) {
		this.id = id;
	}
	
	
	public Order(Integer number, Float money) {
		super();
		this.number = number;
		this.money = money;
	}

	public Order(User user, Integer user_id, Date hour, Integer number, Float money, String bascy, Set appraises) {
		super();
		this.user = user;
		this.user_id = user_id;
		this.hour = hour;
		this.number = number;
		this.money = money;
		this.bascy = bascy;
		this.appraises = appraises;
	}

	public Order(Employee employee, Integer employee_id, Date hour, Integer number, Float money, String bascy,
			Set appraises) {
		super();
		this.employee = employee;
		this.employee_id = employee_id;
		this.hour = hour;
		this.number = number;
		this.money = money;
		this.bascy = bascy;
		this.appraises = appraises;
	}

	public Order(Employee employee, Integer employee_id, User user, Integer user_id, Date hour, Integer number,
			Float money, String bascy, Set appraises) {
		super();
		this.employee = employee;
		this.employee_id = employee_id;
		this.user = user;
		this.user_id = user_id;
		this.hour = hour;
		this.number = number;
		this.money = money;
		this.bascy = bascy;
		this.appraises = appraises;
	}

	public Order(int id, Employee employee, User user, Date hour, Integer number, Float money, String bascy,
			Set appraises) {
		this.id = id;
		this.employee = employee;
		this.user = user;
		this.hour = hour;
		this.number = number;
		this.money = money;
		this.bascy = bascy;
		this.appraises = appraises;
	}

	

	public Order(Integer employee_id, Integer user_id, Date hour, Integer number, Float money, String bascy) {
		super();
		this.employee_id = employee_id;
		this.user_id = user_id;
		this.hour = hour;
		this.number = number;
		this.money = money;
		this.bascy = bascy;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getHour() {
		return this.hour;
	}

	public void setHour(Date hour) {
		this.hour = hour;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public Float getMoney() {
		return this.money;
	}

	public void setMoney(Float money) {
		this.money = money;
	}

	public String getBascy() {
		return this.bascy;
	}

	public void setBascy(String bascy) {
		this.bascy = bascy;
	}

	public Set getAppraises() {
		return this.appraises;
	}

	public void setAppraises(Set appraises) {
		this.appraises = appraises;
	}

}
