package com.direct.est.entity;
// Generated 2019-12-13 10:36:57 by Hibernate Tools 5.4.7.Final

/**
 * 用户标签
 * Userlabel generated by hbm2java
 */
public class Userlabel implements java.io.Serializable {

	private int id;
	private Label label;
	private Integer label_id;
	private User user;
	private Integer user_id;

	public Userlabel() {
	}

	public Userlabel(int id) {
		this.id = id;
	}

	public Userlabel(int id, Label label, User user) {
		this.id = id;
		this.label = label;
		this.user = user;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Label getLabel() {
		return this.label;
	}

	public void setLabel(Label label) {
		this.label = label;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
